disabled_rules:
  - trailing_whitespace
  - force_cast
  - todo
  - attributes

opt_in_rules:
  - explicit_init
  - closure_spacing
  - attributes

included:
  - MealHunter

excluded:
  - Pods
  - Carthage
  - Build

line_length: 120
indentation: 4

type_name:
  min_length: 3
  max_length: 40

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - x
    - y

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

analyzer_rules:
  - unused_import
